#!/usr/bin/python
import os.path
import subprocess
import crypt

#variables
checklog_file_ = "checklog_file_"
file_log_name = "users-create.yml"
dict_user = {}
list_groups = []
#function for befin yml file
def BeginFile():
        with open (file_log_name, 'a') as f: f.write ("---" + '\n')
        with open (file_log_name, 'a') as f: f.write ("- hosts: all" + '\n')
        with open (file_log_name, 'a') as f: f.write ("  remote_user: USER" + '\n')
        with open (file_log_name, 'a') as f: f.write ("  sudo: yes" + '\n')
        with open (file_log_name, 'a') as f: f.write ("  tasks:" + '\n')

#this for GECOS function for getting SD nameber and email's user
def GetSDname():
        sd_data = raw_input('Enter SD ticket name: ')
        while 'SD' not in sd_data:
                sd_data = raw_input('Please enter SD exmple SD0000001: ')
        dict_user.update({'SD': sd_data})
        return sd_data

def GetEmailUser():
        var_email_user = raw_input('Enter email for user: ')
        while '@' not in var_email_user:
                var_email_user = raw_input('Please enter email exmple user@domainname.domain: ')
        dict_user.update({'email_user': var_email_user})
        return var_email_user

def ConstructComment():
        UserEmail = GetEmailUser()
        SDname= GetSDname()
        var_comment = (" comment=" + "'" + SDname  + " " + UserEmail  + "'")
        return var_comment

# function for get user name with checking empty fileld or not
def GetUserName():
        username_data = raw_input('Enter User name: ')
        while len(username_data) == 0:
                username_data = raw_input('Enter User name cannot be empty: ')
        dict_user.update({'user_name': username_data})
        return username_data
#function for construct part of line yml relative to username
def ConstructUser():
        UserName = GetUserName()
        var_username= ("      " + "- user: name=" + "'" + UserName + "'")
        return var_username
###

def GetHomeDir():
        var_home = raw_input('Enter home if home is not standard otherwise home dir will be: ' + "/home/"+ dict_user.get('user_name') + ' :')
        if var_home == '':
                var_home = "/home/" + dict_user.get('user_name')
        dict_user.update({'home_user': var_home})
        return var_home

def GetShell():
        var_shell = raw_input('Enter shell with specify standard otherwise home dir will be: ' + "/bin/bash" + ' :')
        if var_shell == '':
                var_shell = "/bin/bash"
        dict_user.update({'shell': var_shell})
        return var_shell
##### password

def GeneratePassword():
        gen_plain_password = "date +%s | sha256sum | base64 | head -c 21"
        plain_password = subprocess.check_output(['bash','-c', gen_plain_password])
        var_hash = crypt.crypt(plain_password, crypt.mksalt())
        dict_user.update({'plain_password': plain_password, 'hash_password':var_hash})
        return var_hash
GeneratePassword()
#####

#######
#add groups
def GetGroups():
        var_groups = raw_input('Enter Groups:')
        if var_groups != '':
                dict_user.update({'groups': var_groups})
        else:
                var_groups=''
                dict_user.update({'groups': var_groups})
        return var_groups


GetGroups()


######

def CreateYml():
        UserName = ConstructUser()
        Comment = ConstructComment()
        HomeUser = GetHomeDir()
        var_HomeUser = " home=" + "'"+ dict_user.get('home_user')+"'"
        Shell = GetShell()
        var_Shell = " shell=" + "'" + Shell + "'"
        var_password =" password=" + "'" + GeneratePassword() + "'"
        var_groups = " group=" + "'" + dict_user.get('groups') + "'"
        with open (file_log_name, 'a') as f: f.write (UserName  + Comment + var_HomeUser  + var_Shell + var_password + '\n')
        print "var_groups",type(var_groups),var_groups
        if  dict_user.get('groups') != '':
                print "groups ",dict_user.get('groups')
                with open (file_log_name, 'a') as f: f.write (UserName  + Comment + var_HomeUser  + var_Shell + var_groups+ '\n')
        else:
                print ""
                with open (file_log_name, 'a') as f: f.write (UserName  + Comment + var_HomeUser  + var_Shell + '\n')


def CheckerYmlFile():
        if os.path.isfile(file_log_name) == False:
                BeginFile()
                CreateYml()
        else:
                CreateYml()
CheckerYmlFile()

def checklog_file():
        with open (checklog_file_, 'a') as f: f.write (str(dict_user) + '\n')

checklog_file()
